name: build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Lint go code
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
      - name: Build server executable
        run: go build
      - name: Run tests
        run: go test ./... -v
