name: Unit test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Golang
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Checksum
        id: checksum
        run: |
          checksum=$(
            {
              sha256sum go.mod go.sum
              find . -type f -name "*.go" -print0 | sort -z | xargs -0 sha256sum
            } | sha256sum | awk '{print $1}'
          )
          echo "checksum=$checksum" >> "$GITHUB_OUTPUT"

      - name: Restore Go module cache
        id: go-mod-cache
        uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ~/go/pkg/mod
          key: go-mod-${{ hashFiles('go.sum') }}

      - name: Restore Go build cache
        id: go-build-cache
        uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ~/.cache/go-build
          key: unit-test-${{ steps.checksum.outputs.checksum }}
          restore-keys: |
            unit-test-

      - name: Run tests
        run: |
          make unit-test-cover

      - name: Save Go module cache
        if: steps.go-mod-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ~/go/pkg/mod
          key: go-mod-${{ hashFiles('go.sum') }}

      - name: Save Go build cache
        if: steps.go-build-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ~/.cache/go-build
          key: unit-test-${{ steps.checksum.outputs.checksum }}

      - name: Generate coverage report
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: go-coverage-report-${{ matrix.go-version-alias }}
          path: coverage.html
