name: image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  workflow_dispatch:
  release:
    types: ["published"]

jobs:
  docker:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      # Used to get revision information in steps carried out prior to the image build.
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Ensure the build step can get hold of the version information.
      - run: echo "VERSION=$(git describe --tags --always --abbrev=0)" >> $GITHUB_ENV
      - run: echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: docker/build-push-action@v6
        with:
          build-args: |
            "VERSION=${{ env.VERSION }},COMMIT=${{ env.COMMIT }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
