name: Main branch protection

run-name: "Main branch protection: ${{ github.event.head_commit.message }}"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  go:
    name: Golang
    uses: ./.github/workflows/go.yaml

  image:
    name: Image
    needs: go
    uses: ./.github/workflows/image.yaml
    with:
      push: false
